//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActNivEdu
    {
        public int id { get; set; }
        public int ActividadId { get; set; }
        public int NivelEducativoId { get; set; }
        public double Mutipliacdor { get; set; }
    
        public virtual ActividadesPuestoDeTrabajo ActividadesPuestoDeTrabajo { get; set; }
        public virtual NivelEducativo NivelEducativo { get; set; }
    }
}
