//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centros
    {
        public Centros()
        {
            this.RespuestasCalculadora = new HashSet<RespuestasCalculadora>();
            this.ResultadoCalculadora = new HashSet<ResultadoCalculadora>();
            this.RespuestaPila = new HashSet<RespuestaPila>();
        }
    
        public int Id { get; set; }
        public string CentroEmpleo { get; set; }
        public string UserID { get; set; }
        public string Dominio { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<RespuestasCalculadora> RespuestasCalculadora { get; set; }
        public virtual ICollection<ResultadoCalculadora> ResultadoCalculadora { get; set; }
        public virtual ICollection<RespuestaPila> RespuestaPila { get; set; }
    }
}
