//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int id { get; set; }
        public string DocumentoNumero { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public string UsuerID { get; set; }
        public int CentroID { get; set; }
        public string TipoDocumento { get; set; }
    
        public virtual TipoDocumento TipoDocumento1 { get; set; }
    }
}
