//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsAudit
    {
        public System.Guid Id { get; set; }
        public string InstanciaServidor { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string IpRequest { get; set; }
        public string Agent { get; set; }
        public string JsonRequest { get; set; }
        public string JsonResponse { get; set; }
        public string Operacion { get; set; }
        public string DataRequest { get; set; }
    }
}
