//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilEmpleosEntities1 : DbContext
    {
        public MilEmpleosEntities1()
            : base("name=MilEmpleosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActividadesPuestoDeTrabajo> ActividadesPuestoDeTrabajo { get; set; }
        public virtual DbSet<ActividadNivEduDes> ActividadNivEduDes { get; set; }
        public virtual DbSet<ActividadNivEduHab> ActividadNivEduHab { get; set; }
        public virtual DbSet<ActNivEdu> ActNivEdu { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Centros> Centros { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<ContenidoActividadFormacion> ContenidoActividadFormacion { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<Destrezas> Destrezas { get; set; }
        public virtual DbSet<Habilidad> Habilidad { get; set; }
        public virtual DbSet<JovenesPorTutor> JovenesPorTutor { get; set; }
        public virtual DbSet<municipality> municipality { get; set; }
        public virtual DbSet<NivelEducativo> NivelEducativo { get; set; }
        public virtual DbSet<PassPrestadores> PassPrestadores { get; set; }
        public virtual DbSet<Ponderacion> Ponderacion { get; set; }
        public virtual DbSet<PonderacionMunicipio> PonderacionMunicipio { get; set; }
        public virtual DbSet<RespuestasCalculadora> RespuestasCalculadora { get; set; }
        public virtual DbSet<ResultadoCalculadora> ResultadoCalculadora { get; set; }
        public virtual DbSet<SalarioAdicionalRango> SalarioAdicionalRango { get; set; }
        public virtual DbSet<TipoConocimientoRequerido> TipoConocimientoRequerido { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<Pila> Pila { get; set; }
        public virtual DbSet<RespuestaPila> RespuestaPila { get; set; }
        public virtual DbSet<actulizacionPila> actulizacionPila { get; set; }
    }
}
