//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilEmpleosEntities : DbContext
    {
        public MilEmpleosEntities()
            : base("name=MilEmpleosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Centros> Centros { get; set; }
        public virtual DbSet<NivelFormacion> NivelFormacion { get; set; }
        public virtual DbSet<Opciones> Opciones { get; set; }
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<WSPila> WSPila { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Preguntas> Preguntas { get; set; }
        public virtual DbSet<RespuestaPila> RespuestaPila { get; set; }
    }
}
