//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipality
    {
        public municipality()
        {
            this.RespuestasCalculadora = new HashSet<RespuestasCalculadora>();
        }
    
        public string IdCodigo { get; set; }
        public string nombre { get; set; }
        public string department_id { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<RespuestasCalculadora> RespuestasCalculadora { get; set; }
        public virtual PonderacionMunicipio PonderacionMunicipio { get; set; }
    }
}
