//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassPrestadores
    {
        public int Id { get; set; }
        public string Prestador { get; set; }
        public string ClaveINI { get; set; }
        public string UsurioCorreo { get; set; }
    }
}
