//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pila
    {
        public int id { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<int> TiempoTotalRegistroMeses { get; set; }
        public Nullable<System.DateTime> ultimo_periodo_cotizado_fecha_inicio { get; set; }
        public Nullable<System.DateTime> ultimo_periodo_cotizado_fecha_fin { get; set; }
        public Nullable<int> Meses_ultimo_periodo_cotizado { get; set; }
    }
}
