//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pila
    {
        public int id { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<int> TiempoTotalRegistroMeses { get; set; }
        public Nullable<System.DateTime> ultimo_periodo_cotizado_fecha_inicio { get; set; }
        public Nullable<System.DateTime> ultimo_periodo_cotizado_fecha_fin { get; set; }
        public Nullable<int> Meses_ultimo_periodo_cotizado { get; set; }
    }
}
