//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaPila
    {
        public int id { get; set; }
        public bool Registrado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaRespuestaPila { get; set; }
        public int TiempoTotalRegistroMeses { get; set; }
        public System.DateTime UltimoPeriodo_fecha_inicio { get; set; }
        public System.DateTime UltimoPeriodo_fecha_fin { get; set; }
        public Nullable<int> Meses_UltimoPeriodo { get; set; }
        public string TipoDocumento { get; set; }
        public string NoDocumento { get; set; }
        public string UserId { get; set; }
        public int CentroId { get; set; }
        public int ConsutaId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Centros Centros { get; set; }
    }
}
