//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoCalculadora
    {
        public System.Guid id { get; set; }
        public double CapitalHumano { get; set; }
        public double CaracteristicasEmpresa { get; set; }
        public double CaracteristicasPuesto { get; set; }
        public double Total { get; set; }
        public string UserId { get; set; }
        public int CentroId { get; set; }
        public int RespuestasCalculadoraId { get; set; }
        public System.DateTime FechaCalculo { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Centros Centros { get; set; }
        public virtual RespuestasCalculadora RespuestasCalculadora { get; set; }
    }
}
