//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoCalculadora
    {
        public System.Guid id { get; set; }
        public double CapitalHumano { get; set; }
        public double CaracteristicasEmpresa { get; set; }
        public double CaracteristicasPuesto { get; set; }
        public double Total { get; set; }
        public string UserId { get; set; }
        public int CentroId { get; set; }
        public int RespuestasCalculadoraId { get; set; }
        public System.DateTime FechaCalculo { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Centros Centros { get; set; }
        public virtual RespuestasCalculadora RespuestasCalculadora { get; set; }
    }
}
