//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilEmpleos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSPila
    {
        public int id { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public int TiempoTotalRegistroMeses { get; set; }
        public int MaximoMesesContinuos { get; set; }
        public System.DateTime MaximoMesesContinuos_fecha_inicio { get; set; }
        public System.DateTime MaximoMesesContinuos_fecha_fin { get; set; }
        public int Meses_UltimoPeriodoSuperior6Meses { get; set; }
        public System.DateTime Meses_UltimoPeriodoSuperior6Meses_fecha_inicio { get; set; }
        public System.DateTime Meses_UltimoPeriodoSuperior6Meses_fecha_fin { get; set; }
        public string Empleador_UltimoPeriodo { get; set; }
        public int Meses_PenultimoPeriodoSuperior6Meses { get; set; }
        public System.DateTime Meses_PenultimoPeriodoSuperior6Meses_fecha_inicio { get; set; }
        public System.DateTime Meses_PenultimoPeriodoSuperior6Meses_fecha_fin { get; set; }
        public string Empleador_PenultimoPeriodo { get; set; }
    }
}
